#!/bin/bash

_pcache_completion() {
	local cur prev commands sub_commands
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	commands="cache-start cache-stop cache-list backing-start backing-stop backing-list"

	case "${COMP_CWORD}" in
		1)
			COMPREPLY=( $(compgen -W "${commands}" -- "$cur") )
			;;
		*)
			case "${COMP_WORDS[1]}" in
				cache-start)
					sub_commands="-p --path -f --format -F --force -h --help"
					COMPREPLY=( $(compgen -W "${sub_commands}" -- "$cur") )
					;;
				cache-stop)
					sub_commands="-c --cache -h --help"
					COMPREPLY=( $(compgen -W "${sub_commands}" -- "$cur") )
					;;
				cache-list)
					sub_commands="-h --help"
					COMPREPLY=( $(compgen -W "${sub_commands}" -- "$cur") )
					;;
				backing-start)
					sub_commands="-c --cache -p --path -q --queues -s --cache-size -h --help"
					COMPREPLY=( $(compgen -W "${sub_commands}" -- "$cur") )
					;;
				backing-stop)
					sub_commands="-c --cache -b --backing -h --help"
					COMPREPLY=( $(compgen -W "${sub_commands}" -- "$cur") )
					;;
				backing-list)
					sub_commands="-c --cache -h --help"
					COMPREPLY=( $(compgen -W "${sub_commands}" -- "$cur") )
					;;
			esac
			;;
	esac
}

complete -F _pcache_completion pcache
